### PR TITLE
connected zuul to this repository

### PR DESCRIPTION
**Pull request by tibeer**
Signed-off-by: Tim Beermann <beermann@osism.tech>

### CODE REVIEW

**Comment by osfrickler** [comment]
recheck added repo to zuul

**Comment by osfrickler** [comment]
recheck

**Review by osfrickler — COMMENTED** [review]
Why are you adding a hidden directory? Shouldn't the playbooks end up in the existing "playbooks" directory?

Maybe also use zuul.d/{job,project}.yaml, no need to hide those, either.

Finally, the role itself seems not to be finding any work to do, not sure if you'd want to fix that within this PR or in a followup. You'd also need to make sure that the log file ends up within the build logs.

**Comment by tibeer** [comment]
They are in a hidden directory because i was used to it ^^. I like the idea of using a zuul.d directory. Using a normal "playbooks" directory might cause misleading information for people from outside which are unaware of zuul.

**Pull request closed without merging**
